// examples/vue/EmailEditor.vue
<template>
  <div class="email-editor-vue">
    <div class="editor-toolbar" v-if="showToolbar">
      <div class="toolbar-left">
        <slot name="toolbar-left">
          <h3>{{ title }}</h3>
        </slot>
      </div>
      <div class="toolbar-right">
        <button class="btn btn-secondary" @click="handlePreviewHTML">
          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" width="16" height="16"><polyline points="16 18 22 12 16 6"/><polyline points="8 6 2 12 8 18"/></svg>
          Ver HTML
        </button>
        <button class="btn btn-secondary" @click="handleGetJSON">
          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" width="16" height="16"><path d="M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z"/></svg>
          JSON
        </button>
        <slot name="toolbar-actions" />
      </div>
    </div>

    <textarea ref="editorEl" style="display:none" />

    <!-- HTML Preview Modal -->
    <Teleport to="body">
      <div class="modal-overlay" v-if="showPreview" @click.self="showPreview = false">
        <div class="modal-panel">
          <div class="modal-header">
            <h3>{{ previewTitle }}</h3>
            <div class="modal-actions">
              <button class="btn btn-sm" @click="copyPreview">
                {{ copied ? 'Copiado!' : 'Copiar' }}
              </button>
              <button class="btn-close" @click="showPreview = false">&times;</button>
            </div>
          </div>
          <pre class="modal-code">{{ previewContent }}</pre>
        </div>
      </div>
    </Teleport>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, onBeforeUnmount, watch } from 'vue';
import { EmailEditor } from '@tag/email-editor';
import type { EmailEditorOptions } from '@tag/email-editor';

// ============================================
// Props
// ============================================
interface Props {
  modelValue?: string;
  height?: string;
  tags?: string[];
  templates?: EmailEditorOptions['templates'];
  title?: string;
  showToolbar?: boolean;
  onUpload?: EmailEditorOptions['onUpload'];
}

const props = withDefaults(defineProps<Props>(), {
  modelValue: '',
  height: '600px',
  tags: () => [],
  title: 'Email Editor',
  showToolbar: true,
});

// ============================================
// Emits
// ============================================
const emit = defineEmits<{
  'update:modelValue': [html: string];
  'ready': [editor: EmailEditor];
  'change': [html: string];
}>();

// ============================================
// State
// ============================================
const editorEl = ref<HTMLTextAreaElement | null>(null);
let editor: EmailEditor | null = null;

const showPreview = ref(false);
const previewTitle = ref('');
const previewContent = ref('');
const copied = ref(false);

// ============================================
// Lifecycle
// ============================================
onMounted(() => {
  if (!editorEl.value) return;

  // Set initial value
  if (props.modelValue) {
    editorEl.value.value = props.modelValue;
  }

  editor = new EmailEditor({
    target: editorEl.value,
    height: props.height,
    tags: props.tags,
    templates: props.templates,
    onUpload: props.onUpload,
    onChange: (html: string) => {
      emit('update:modelValue', html);
      emit('change', html);
    },
    onReady: () => {
      emit('ready', editor!);
    },
  });
});

onBeforeUnmount(() => {
  editor?.destroy();
  editor = null;
});

// ============================================
// Watchers
// ============================================
// If parent changes modelValue externally, update editor
let lastEmitted = '';
watch(() => props.modelValue, (val) => {
  if (val && val !== lastEmitted && editor) {
    editor.setContent(val);
  }
});

// ============================================
// Methods
// ============================================
function handlePreviewHTML() {
  previewTitle.value = 'HTML Output';
  previewContent.value = editor?.getHTML() || '';
  showPreview.value = true;
}

function handleGetJSON() {
  previewTitle.value = 'JSON Output';
  previewContent.value = JSON.stringify(editor?.getJSON() || {}, null, 2);
  showPreview.value = true;
}

async function copyPreview() {
  await navigator.clipboard.writeText(previewContent.value);
  copied.value = true;
  setTimeout(() => (copied.value = false), 2000);
}

// ============================================
// Expose public API
// ============================================
defineExpose({
  getHTML: () => editor?.getHTML() ?? '',
  getMJML: () => editor?.getMJML() ?? '',
  getJSON: () => editor?.getJSON() ?? {},
  setContent: (content: string | object) => editor?.setContent(content),
  loadTemplate: (id: string) => editor?.loadTemplate(id),
  setDevice: (device: 'Desktop' | 'Mobile') => editor?.setDevice(device),
  getEditor: () => editor?.getEditor(),
});
</script>

<style scoped>
.email-editor-vue {
  display: flex;
  flex-direction: column;
  width: 100%;
}

.editor-toolbar {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 12px 16px;
  background: #fff;
  border: 1px solid #e4e7ec;
  border-bottom: none;
  border-radius: 10px 10px 0 0;
}

.editor-toolbar h3 {
  font-size: 15px;
  font-weight: 600;
  color: #1a1d23;
  margin: 0;
}

.toolbar-right {
  display: flex;
  gap: 6px;
  align-items: center;
}

.btn {
  display: inline-flex;
  align-items: center;
  gap: 6px;
  padding: 7px 14px;
  border: 1.5px solid #e4e7ec;
  border-radius: 6px;
  background: #fff;
  color: #374151;
  font-size: 13px;
  font-weight: 500;
  font-family: inherit;
  cursor: pointer;
  transition: all 0.15s;
}

.btn:hover {
  border-color: #4f46e5;
  color: #4f46e5;
  background: #eef2ff;
}

.btn-sm {
  composes: btn;
  padding: 5px 12px;
  font-size: 12px;
}

.btn-close {
  width: 32px;
  height: 32px;
  display: flex;
  align-items: center;
  justify-content: center;
  border: none;
  border-radius: 6px;
  background: transparent;
  font-size: 20px;
  color: #9ca3af;
  cursor: pointer;
}

.btn-close:hover {
  background: #fee2e2;
  color: #ef4444;
}

/* Modal */
.modal-overlay {
  position: fixed;
  inset: 0;
  background: rgba(0,0,0,0.5);
  backdrop-filter: blur(6px);
  z-index: 10000;
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 32px;
}

.modal-panel {
  background: #fff;
  border-radius: 16px;
  box-shadow: 0 24px 80px rgba(0,0,0,0.2);
  width: 100%;
  max-width: 1100px;
  height: 80vh;
  display: flex;
  flex-direction: column;
  overflow: hidden;
}

.modal-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 16px 24px;
  border-bottom: 1px solid #e4e7ec;
  background: #f8f9fb;
}

.modal-header h3 {
  font-size: 14px;
  font-weight: 600;
  margin: 0;
}

.modal-actions {
  display: flex;
  gap: 8px;
  align-items: center;
}

.modal-code {
  flex: 1;
  overflow: auto;
  margin: 0;
  padding: 24px;
  font-size: 13px;
  line-height: 1.7;
  font-family: 'SF Mono', 'Fira Code', monospace;
  background: #0f172a;
  color: #e2e8f0;
}
</style>

// examples/react/EmailEditor.tsx
import React, {
  useRef,
  useEffect,
  useImperativeHandle,
  forwardRef,
  useState,
  useCallback,
} from 'react';
import { EmailEditor as EmailEditorLib } from '@tag/email-editor';
import type { EmailEditorOptions, EmailTemplate } from '@tag/email-editor';

// ============================================
// Types
// ============================================
export interface EmailEditorProps {
  height?: string;
  tags?: string[];
  templates?: EmailTemplate[];
  initialContent?: string;
  onChange?: (html: string) => void;
  onReady?: (editor: EmailEditorLib) => void;
  onUpload?: EmailEditorOptions['onUpload'];
}

export interface EmailEditorHandle {
  getHTML: () => string;
  getMJML: () => string;
  getJSON: () => object;
  setContent: (content: string | object) => void;
  loadTemplate: (id: string) => void;
  setDevice: (device: 'Desktop' | 'Mobile') => void;
}

// ============================================
// Component
// ============================================
const EmailEditor = forwardRef<EmailEditorHandle, EmailEditorProps>(
  (
    {
      height = '600px',
      tags = [],
      templates,
      initialContent,
      onChange,
      onReady,
      onUpload,
    },
    ref,
  ) => {
    const textareaRef = useRef<HTMLTextAreaElement>(null);
    const editorRef = useRef<EmailEditorLib | null>(null);

    useEffect(() => {
      if (!textareaRef.current) return;

      if (initialContent) {
        textareaRef.current.value = initialContent;
      }

      editorRef.current = new EmailEditorLib({
        target: textareaRef.current,
        height,
        tags,
        templates,
        onUpload,
        onChange,
        onReady: () => {
          if (onReady && editorRef.current) {
            onReady(editorRef.current);
          }
        },
      });

      return () => {
        editorRef.current?.destroy();
        editorRef.current = null;
      };
      // eslint-disable-next-line react-hooks/exhaustive-deps
    }, []);

    useImperativeHandle(ref, () => ({
      getHTML: () => editorRef.current?.getHTML() ?? '',
      getMJML: () => editorRef.current?.getMJML() ?? '',
      getJSON: () => editorRef.current?.getJSON() ?? {},
      setContent: (content) => editorRef.current?.setContent(content),
      loadTemplate: (id) => editorRef.current?.loadTemplate(id),
      setDevice: (device) => editorRef.current?.setDevice(device),
    }));

    return <textarea ref={textareaRef} style={{ display: 'none' }} />;
  },
);

EmailEditor.displayName = 'EmailEditor';

// ============================================
// Preview Modal
// ============================================
interface PreviewModalProps {
  title: string;
  content: string;
  onClose: () => void;
}

function PreviewModal({ title, content, onClose }: PreviewModalProps) {
  const [copied, setCopied] = useState(false);

  const handleCopy = useCallback(async () => {
    await navigator.clipboard.writeText(content);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }, [content]);

  // Close on Escape
  useEffect(() => {
    const handler = (e: KeyboardEvent) => {
      if (e.key === 'Escape') onClose();
    };
    window.addEventListener('keydown', handler);
    return () => window.removeEventListener('keydown', handler);
  }, [onClose]);

  return (
    <div style={styles.overlay} onClick={(e) => e.target === e.currentTarget && onClose()}>
      <div style={styles.modal}>
        <div style={styles.modalHeader}>
          <h3 style={styles.modalTitle}>{title}</h3>
          <div style={styles.modalActions}>
            <button
              style={{
                ...styles.btnCopy,
                ...(copied ? styles.btnCopied : {}),
              }}
              onClick={handleCopy}
            >
              {copied ? 'Copiado!' : 'Copiar'}
            </button>
            <button style={styles.btnClose} onClick={onClose}>
              &times;
            </button>
          </div>
        </div>
        <pre style={styles.code}>{content}</pre>
      </div>
    </div>
  );
}

// ============================================
// Demo App
// ============================================
export function EmailEditorDemo() {
  const editorRef = useRef<EmailEditorHandle>(null);
  const [preview, setPreview] = useState<{ title: string; content: string } | null>(null);

  function showHTML() {
    setPreview({
      title: 'HTML Output',
      content: editorRef.current?.getHTML() ?? '',
    });
  }

  function showJSON() {
    setPreview({
      title: 'JSON Output',
      content: JSON.stringify(editorRef.current?.getJSON() ?? {}, null, 2),
    });
  }

  function handleSave() {
    const html = editorRef.current?.getHTML();
    const json = editorRef.current?.getJSON();
    console.log('HTML para enviar por email:', html);
    console.log('JSON para salvar no banco:', json);
    alert('Email salvo! Veja o console para o output.');
  }

  function handleTemplate(e: React.ChangeEvent<HTMLSelectElement>) {
    const id = e.target.value;
    if (id) editorRef.current?.loadTemplate(id);
  }

  return (
    <div style={styles.app}>
      {/* Header */}
      <header style={styles.header}>
        <h1 style={styles.headerTitle}>
          Email Editor <span style={styles.headerBadge}>React Example</span>
        </h1>
        <div style={styles.headerActions}>
          <button style={styles.headerBtn} onClick={showHTML}>
            Ver HTML
          </button>
          <button style={styles.headerBtn} onClick={showJSON}>
            JSON
          </button>
          <select style={styles.headerBtn} onChange={handleTemplate} defaultValue="">
            <option value="">Template...</option>
            <option value="blank">Em Branco</option>
            <option value="newsletter">Newsletter</option>
            <option value="promotional">Promocional</option>
            <option value="welcome">Boas-vindas</option>
          </select>
          <button style={{ ...styles.headerBtn, background: 'rgba(255,255,255,0.2)' }} onClick={handleSave}>
            Salvar
          </button>
        </div>
      </header>

      {/* Editor */}
      <EmailEditor
        ref={editorRef}
        height="calc(100vh - 56px)"
        tags={['nome', 'email', 'empresa', 'produto', 'preco']}
        onChange={(html) => {
          // html atualizado a cada mudanca
        }}
        onReady={(editor) => {
          console.log('Editor pronto!', editor);
        }}
      />

      {/* Preview Modal */}
      {preview && (
        <PreviewModal
          title={preview.title}
          content={preview.content}
          onClose={() => setPreview(null)}
        />
      )}
    </div>
  );
}

// ============================================
// Styles
// ============================================
const styles: Record<string, React.CSSProperties> = {
  app: {
    minHeight: '100vh',
    background: '#f0f2f5',
    fontFamily: "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
  },
  header: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '0 24px',
    height: 56,
    background: 'linear-gradient(135deg, #4f46e5 0%, #7c3aed 100%)',
    color: 'white',
  },
  headerTitle: {
    fontSize: 16,
    fontWeight: 600,
    margin: 0,
  },
  headerBadge: {
    fontWeight: 400,
    opacity: 0.7,
    marginLeft: 8,
    fontSize: 13,
  },
  headerActions: {
    display: 'flex',
    gap: 8,
    alignItems: 'center',
  },
  headerBtn: {
    padding: '7px 16px',
    border: '1px solid rgba(255,255,255,0.2)',
    borderRadius: 6,
    background: 'rgba(255,255,255,0.1)',
    color: 'white',
    fontSize: 13,
    fontWeight: 500,
    fontFamily: 'inherit',
    cursor: 'pointer',
  },
  overlay: {
    position: 'fixed',
    inset: 0,
    background: 'rgba(0,0,0,0.5)',
    backdropFilter: 'blur(6px)',
    zIndex: 10000,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 32,
  },
  modal: {
    background: '#fff',
    borderRadius: 16,
    boxShadow: '0 24px 80px rgba(0,0,0,0.2)',
    width: '100%',
    maxWidth: 1100,
    height: '80vh',
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
  },
  modalHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '16px 24px',
    borderBottom: '1px solid #e4e7ec',
    background: '#f8f9fb',
  },
  modalTitle: {
    fontSize: 14,
    fontWeight: 600,
    margin: 0,
  },
  modalActions: {
    display: 'flex',
    gap: 8,
    alignItems: 'center',
  },
  btnCopy: {
    padding: '5px 12px',
    border: '1.5px solid #e4e7ec',
    borderRadius: 6,
    background: '#fff',
    color: '#374151',
    fontSize: 12,
    fontWeight: 500,
    fontFamily: 'inherit',
    cursor: 'pointer',
  },
  btnCopied: {
    borderColor: '#10b981',
    color: '#10b981',
    background: '#ecfdf5',
  },
  btnClose: {
    width: 32,
    height: 32,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    border: 'none',
    borderRadius: 8,
    background: 'transparent',
    fontSize: 22,
    color: '#9ca3af',
    cursor: 'pointer',
  },
  code: {
    flex: 1,
    overflow: 'auto',
    margin: 0,
    padding: 24,
    fontSize: 13,
    lineHeight: 1.7,
    fontFamily: "'SF Mono', 'Fira Code', monospace",
    background: '#0f172a',
    color: '#e2e8f0',
  },
};

export default EmailEditor;
